/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

/**
 *
 * @author Annan ID
 */
public class app extends javax.swing.JFrame {

    public app() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Tab1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Tab2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Tab3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        Tab4 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        Tab5 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("barang");

        Tab1.setText("Barang");
        Tab1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tab1ActionPerformed(evt);
            }
        });
        jMenu1.add(Tab1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Kwitansi");

        Tab2.setText("Kwitansi");
        Tab2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tab2ActionPerformed(evt);
            }
        });
        jMenu2.add(Tab2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Faktur");

        Tab3.setText("Faktur");
        Tab3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tab3ActionPerformed(evt);
            }
        });
        jMenu3.add(Tab3);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Pelanggan");

        Tab4.setText("Pelanggan");
        Tab4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tab4ActionPerformed(evt);
            }
        });
        jMenu4.add(Tab4);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Faktur Detail");

        Tab5.setText("Faktur Detail");
        Tab5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tab5ActionPerformed(evt);
            }
        });
        jMenu5.add(Tab5);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tab1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tab1ActionPerformed
        // TODO add your handling code here:
        barang brg = new barang();
        brg.setVisible(true);
    }//GEN-LAST:event_Tab1ActionPerformed

    private void Tab5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tab5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tab5ActionPerformed

    private void Tab4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tab4ActionPerformed
        // TODO add your handling code here:
        pelanggan plg = new pelanggan();
        plg.setVisible(true);
    }//GEN-LAST:event_Tab4ActionPerformed

    private void Tab3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tab3ActionPerformed
        // TODO add your handling code here:
        faktur fkr = new faktur();
        fkr.setVisible(true);
    }//GEN-LAST:event_Tab3ActionPerformed

    private void Tab2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tab2ActionPerformed
        // TODO add your handling code here:
        kwitansi kwt = new kwitansi();
        kwt.setVisible(true);
    }//GEN-LAST:event_Tab2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new app().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Tab1;
    private javax.swing.JMenuItem Tab2;
    private javax.swing.JMenuItem Tab3;
    private javax.swing.JMenuItem Tab4;
    private javax.swing.JMenuItem Tab5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
