/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Annan ID
 */
public class kwitansi extends javax.swing.JFrame {
    public Statement st;
    public ResultSet rs;
    Connection cn = koneksi.koneksi.BukaKoneksi();
    private String tgl;
    
    public kwitansi() {
        initComponents();
        TampilData();
        updateCombo();
    }
    
    private void Bersih(){
        nomer_kwi.setText("");
        tgl_kwi.setDate(null);
        nomor_faktur.setSelectedItem(null);
       
        simpan.setText("Simpan");
        nomer_kwi.setEditable(true);
    }
    
    private void TampilData(){
        try{
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM kwitansi");
            
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Nomor Kwitansi");
            model.addColumn("Tanggal");
            model.addColumn("Nomor Faktur");
            
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            model.setRowCount(0);
            boolean isEmpty = true;
            
            while(rs.next()){
              isEmpty = false;
              Object[]data = {
                rs.getString("nomer_kwi"),
                rs.getString("tgl_kwi"),
                rs.getString("nomor_faktur"),
              };
              model.addRow(data);
              data_kwitansi.setModel(model);
            }
            
            if (isEmpty) {
                JOptionPane.showMessageDialog(null, "Data masih kosong", "Info", JOptionPane.INFORMATION_MESSAGE);
            }
            
        }catch (HeadlessException | SQLException e){    
            JOptionPane.showMessageDialog(null, "Data gagal dimuat. Terjadi kesalahan: " +
            e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void updateCombo(){
        String sql = "SELECT * FROM faktur";
        try {
              st = cn.createStatement();
              rs = st.executeQuery(sql);

               while(rs.next()){
                   nomor_faktur.addItem(rs.getString("nomor_faktur"));
               }
        } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "error");
          }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomer_kwi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        simpan = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        data_kwitansi = new javax.swing.JTable();
        tgl_kwi = new com.toedter.calendar.JDateChooser();
        nomor_faktur = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Kwitansi");

        jLabel2.setText("Nomor kwitansi");

        jLabel3.setText("Tanggal");

        jLabel4.setText("Nomor Faktur");

        simpan.setBackground(new java.awt.Color(0, 204, 51));
        simpan.setForeground(new java.awt.Color(255, 255, 255));
        simpan.setText("Simpan");
        simpan.setMargin(new java.awt.Insets(5, 25, 5, 25));
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        hapus.setBackground(new java.awt.Color(255, 0, 0));
        hapus.setForeground(new java.awt.Color(255, 255, 255));
        hapus.setText("Hapus");
        hapus.setMargin(new java.awt.Insets(5, 25, 5, 25));
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        batal.setBackground(new java.awt.Color(0, 0, 255));
        batal.setForeground(new java.awt.Color(255, 255, 255));
        batal.setText("Batal");
        batal.setMargin(new java.awt.Insets(5, 25, 5, 25));
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });

        data_kwitansi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nomor Kwitansi", "Tanggal Kwitansi", "Nomor Faktur"
            }
        ));
        data_kwitansi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                data_kwitansiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(data_kwitansi);

        tgl_kwi.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tgl_kwiPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(simpan)
                                .addGap(28, 28, 28)
                                .addComponent(batal)
                                .addGap(28, 28, 28)
                                .addComponent(hapus))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tgl_kwi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomer_kwi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomor_faktur, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nomer_kwi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tgl_kwi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomor_faktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(simpan)
                            .addComponent(batal)
                            .addComponent(hapus)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(183, 183, 183))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        try{
            st=cn.createStatement();
            String nomorFaktur = nomor_faktur.getSelectedItem().toString();
            if(nomer_kwi.getText().equals("") || tgl.isEmpty() || nomorFaktur.isEmpty()){
                JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong", "Validasi Data",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            if("Simpan".equals(simpan.getText())){
               String cek = "SELECT * from kwitansi WHERE nomer_kwi = '" + nomer_kwi.getText() + "'";
               rs = st.executeQuery(cek);
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "Upsss....ID ini sudah ada");
                }else{
                    String sql = "INSERT INTO kwitansi VALUES ('" + nomer_kwi.getText()+
                                 "','" + tgl + 
                                 "','" + nomorFaktur + "')";
                    st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                    Bersih();
                    TampilData();
                }
            }else{
                String update = "UPDATE kwitansi SET tgl_kwi = ' " + tgl  +
                                "', nomor_faktur = '" + nomorFaktur +
                                "' WHERE nomer_kwi = '" + nomer_kwi.getText() + "'";
                st.executeUpdate(update);
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                Bersih();
                TampilData();
            }
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
         if(nomer_kwi.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Silahkan Pilih Data yang akan dihapus !");
        } else {
                int jawab = JOptionPane.showConfirmDialog(null, "Data ini akan dihapus, lanjutkan??", "Konfirmasi", JOptionPane.YES_NO_OPTION);
                if(jawab == 0) {
                    try {
                        st = cn.createStatement();
                        String sql = "DELETE FROM kwitansi WHERE nomer_kwi = '" + nomer_kwi.getText() + "'";
                        st.executeUpdate(sql);
                        JOptionPane.showMessageDialog(null, "Data Berhasil dihapus");
                        TampilData();
                        Bersih();
                    } catch(HeadlessException | SQLException e) {
                        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
                    }
                }
            }
    }//GEN-LAST:event_hapusActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
        if(nomer_kwi.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Silahlan Pilih Data yang akan dihapus !");
        }else{
            int jawab = JOptionPane.showConfirmDialog(null, 
                    "Data ini akan dihapus, lanjutkan??","Konfirmasi",
                    JOptionPane.YES_NO_OPTION);
            if(jawab == 0){
                try{
                    st = cn.createStatement();
                    String sql = "DELETE FROM kwitansi WHERE nomer_kwi = '" + nomer_kwi.getText() + "'";
                    st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Data Berhasil dihapus");
                    TampilData();
                    Bersih();
                    
                }catch(HeadlessException | SQLException e){
                    JOptionPane.showMessageDialog(null, "error");
                }
            }
        }
    }//GEN-LAST:event_batalActionPerformed

    private void tgl_kwiPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tgl_kwiPropertyChange
        // TODO add your handling code here:
        if(tgl_kwi.getDate()!= null){
            SimpleDateFormat format_tgl = new SimpleDateFormat("yyyy-MM-dd");
            tgl = format_tgl.format(tgl_kwi.getDate());
        }
    }//GEN-LAST:event_tgl_kwiPropertyChange

    private void data_kwitansiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data_kwitansiMouseClicked
        // TODO add your handling code here:
        nomer_kwi.setText(data_kwitansi.getValueAt(data_kwitansi.getSelectedRow(),0).toString());
        String tanggalDariTabel = data_kwitansi.getValueAt(data_kwitansi.getSelectedRow(), 1).toString();
        nomor_faktur.setSelectedItem(data_kwitansi.getValueAt(data_kwitansi.getSelectedRow(),2).toString());
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd"); // Sesuaikan format tanggal dari tabel
           try {
                java.util.Date tanggal = sdf.parse(tanggalDariTabel);
                tgl_kwi.setDate(tanggal); // Menggunakan variabel 'tgl_kwi' yang merupakan JDateChooser
           }catch (java.text.ParseException ex) {
               JOptionPane.showMessageDialog(null, "error");
            }
        
        nomer_kwi.setEditable(false);
        simpan.setText("Ubah");
    }//GEN-LAST:event_data_kwitansiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kwitansi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kwitansi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kwitansi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kwitansi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new kwitansi().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JTable data_kwitansi;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomer_kwi;
    private javax.swing.JComboBox<String> nomor_faktur;
    private javax.swing.JButton simpan;
    private com.toedter.calendar.JDateChooser tgl_kwi;
    // End of variables declaration//GEN-END:variables
}
